---
# tasks file for base

- name: Ensure aptitude installed, for Ansible compatibility on Ubuntu 16.04
  apt: name=aptitude update_cache=no
  become: yes

- name: Update base packages
  apt: upgrade=safe update_cache=yes cache_valid_time=1800
  become: yes

- name: Get python-basics,git
  apt: name={{item}} update_cache=yes cache_valid_time=1800
  become: yes
  with_items: "{{ lookup('file', 'ubuntu-apt-deps.txt').split() }}"

- name: Set timezone to UTC
  shell: timedatectl set-timezone UTC
  when: ansible_date_time.tz != "UTC"
  become: yes

